const data = [
  {
    objectID: 764095,
    isHighlight: true,
    accessionNumber: "2018.652.5",
    accessionYear: "2018",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/ad/original/DP-18755-007.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/ad/web-large/DP-18755-007.jpg",
    additionalImages: [],
    constituents: [
      {
        constituentID: 169986,
        role: "Artist",
        name: "Unknown",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500125274",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q24238356",
        gender: "",
      },
    ],
    department: "The American Wing",
    objectName: "Painting",
    title: 'Christ Carrying the Cross, called "The Lord of the Fall"',
    culture: "Peru (Cuzco)",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Unknown",
    artistDisplayBio: "",
    artistSuffix: "Cuzco Artist (Peru, second half 18th century)",
    artistAlphaSort: "Unknown",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q24238356",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500125274",
    objectDate: "ca. 1770–75",
    objectBeginDate: 1770,
    objectEndDate: 1775,
    medium: "Oil and gold on canvas",
    dimensions: "65 × 48 in. (165.1 × 121.9 cm)",
    measurements: [
      {
        elementName: "Framed",
        elementDescription: null,
        elementMeasurements: {
          Height: 174.5,
          Width: 131,
        },
      },
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 165.10033,
          Width: 121.92024,
        },
      },
    ],
    creditLine:
      "Gift of James Kung Wei Li, in memory of Ambassador and Mme Ti-Tsun Li, Republic of China, 2018",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-06-02T12:28:57.13Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/764095",
    tags: [
      {
        term: "Christ",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000087",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q642420",
      },
      {
        term: "Angels",
        AAT_URL: "http://vocab.getty.edu/page/aat/300379004",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q235113",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q104413133",
    isTimelineWork: false,
    GalleryNumber: "757",
  },
  {
    objectID: 38945,
    isHighlight: true,
    accessionNumber: "1982.220.9",
    accessionYear: "1982",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/as/original/DT5250.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/as/web-large/DT5250.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/as/original/LC-1982_220_9_001.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/DT7389.jpg",
    ],
    constituents: null,
    department: "Asian Art",
    objectName: "Figure",
    title: "Hanuman Conversing",
    culture: "India (Tamil Nadu)",
    period: "Chola period",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "11th century",
    objectBeginDate: 1000,
    objectEndDate: 1099,
    medium: "Copper alloy",
    dimensions: "H. 25 3/8 in. (64.5 cm); W. 7 1/4 in. (18.4 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 64.13513,
        },
      },
    ],
    creditLine:
      "Purchase, Bequests of Mary Clarke Thompson, Fanny Shapiro, Susan Dwight Bliss, Isaac D. Fletcher, William Gedney Beatty, John L. Cadwalader and Kate Read Blacque, Gifts of Mrs. Samuel T. Peters, Ida H. Ogilvie, Samuel T. Peters and H. R. Bishop, F. C. Bishop and O. M. Bishop, Rogers, Seymour and Fletcher Funds, and other gifts, funds and bequests from various donors, by exchange, 1982",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Sculpture",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-08-31T04:55:22.863Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/38945",
    tags: [
      {
        term: "Deities",
        AAT_URL: "http://vocab.getty.edu/page/aat/300343850",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q178885",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q83562134",
    isTimelineWork: true,
    GalleryNumber: "240",
  },
  {
    objectID: 471853,
    isHighlight: false,
    accessionNumber: "67.153",
    accessionYear: "1967",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/cl/original/DP102902.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/cl/web-large/DP102902.jpg",
    additionalImages: [],
    constituents: null,
    department: "The Cloisters",
    objectName: "Sculpture",
    title: "Enthroned Virgin and Child",
    culture: "French",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "1150–1200",
    objectBeginDate: 1150,
    objectEndDate: 1200,
    medium: "Walnut with gesso, paint, tin leaf, and traces of linen",
    dimensions: "27 × 11 1/4 × 11 in. (68.6 × 28.6 × 27.9 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 27.940056,
          Height: 68.5801,
          Width: 28.575058,
        },
      },
    ],
    creditLine:
      "The Cloisters Collection and James J. Rorimer  Memorial Fund, 1967",
    geographyType: "Made in",
    city: "",
    state: "Auvergne",
    county: "",
    country: "France",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Sculpture",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-02-15T04:42:19.267Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/471853",
    tags: [
      {
        term: "Madonna and Child",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000052",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q9309699",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q20201067",
    isTimelineWork: false,
    GalleryNumber: "004",
  },
  {
    objectID: 500194,
    isHighlight: true,
    accessionNumber: "2019.593",
    accessionYear: "2019",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 162244,
        role: "Artist",
        name: "Pablo Picasso",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500009666",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q5593",
        gender: "",
      },
    ],
    department: "Modern and Contemporary Art",
    objectName: "Painting",
    title: "Woman in a Chemise in an Armchair",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Pablo Picasso",
    artistDisplayBio: "Spanish, Malaga 1881–1973 Mougins, France",
    artistSuffix: "",
    artistAlphaSort: "Picasso, Pablo",
    artistNationality: "Spanish",
    artistBeginDate: "1881",
    artistEndDate: "1973",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q5593",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500009666",
    objectDate: "Paris, late 1913–early 1914",
    objectBeginDate: 1913,
    objectEndDate: 1914,
    medium: "Oil on canvas",
    dimensions: "59 × 39 1/8 in. (149.9 × 99.4 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Height: 149.8603,
          Width: 99.3777,
        },
      },
    ],
    creditLine:
      "Leonard A. Lauder Cubist Collection, Gift of Leonard A. Lauder, in celebration of the Museum’s 150th Anniversary, 2019",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Paintings",
    rightsAndReproduction:
      "© 2022 Estate of Pablo Picasso / Artists Rights Society (ARS), New York",
    linkResource: "",
    metadataDate: "2022-07-06T04:56:00.72Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/500194",
    tags: [
      {
        term: "Female Nudes",
        AAT_URL: "http://vocab.getty.edu/page/aat/300189568",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q40446",
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "908",
  },
  {
    objectID: 544454,
    isHighlight: false,
    accessionNumber: "16.10.224",
    accessionYear: "1916",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/eg/original/DP115767.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/eg/web-large/DP115767.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/eg/original/DP115768.jpg",
    ],
    constituents: null,
    department: "Egyptian Art",
    objectName: "Bust, queen, seated, vulture",
    title: "Upper Part of the Seated Statue of a Queen",
    culture: "",
    period: "New Kingdom",
    dynasty: "Late Dynasty 17–Early Dynasty 18",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "ca. 1580–1550 B.C.",
    objectBeginDate: -1580,
    objectEndDate: -1580,
    medium: "Indurated limestone, paint",
    dimensions: "H. 28 cm (11 in.); W. 17.8 cm (7 in.); D. 10 cm (3 15/16 in.)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 13,
          Height: 30.5,
          Width: 18.5,
        },
      },
    ],
    creditLine: "Rogers Fund, 1916",
    geographyType: "From",
    city: "",
    state: "",
    county: "",
    country: "Egypt",
    region: "Upper Egypt, Thebes",
    subregion: "Asasif",
    locale: "Courtyard CC 41, radim",
    locus: "",
    excavation: "MMA excavations, 1915–16",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-03-26T05:12:23.83Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/544454",
    tags: [
      {
        term: "Queens",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025483",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q16511993",
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: true,
    GalleryNumber: "115",
  },
  {
    objectID: 461607,
    isHighlight: false,
    accessionNumber: "1975.1.2158",
    accessionYear: "1975",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/rl/original/DT2839.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/rl/web-large/DT2839.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/rl/original/86C_043r3_p.jpg",
      "https://images.metmuseum.org/CRDImages/rl/original/86C_FRTS3R3M.jpg",
      "https://images.metmuseum.org/CRDImages/rl/original/86D_043Vr1.jpg",
    ],
    constituents: [
      {
        constituentID: 161672,
        role: "Artist",
        name: "Possibly workshop of Benedetto da Maiano",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500006675",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q675619",
        gender: "",
      },
    ],
    department: "Robert Lehman Collection",
    objectName: "Frame",
    title: "Tondo mirror frame",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "Possibly workshop of",
    artistDisplayName: "Benedetto da Maiano",
    artistDisplayBio: "Italian, Maiano 1442–1497 Florence",
    artistSuffix: "",
    artistAlphaSort: "Benedetto da Maiano",
    artistNationality: "Italian",
    artistBeginDate: "1442",
    artistEndDate: "1497",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q675619",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500006675",
    objectDate: "ca. 1480",
    objectBeginDate: 1480,
    objectEndDate: 1480,
    medium: "Stucco squeeze, blown convex mirror, gilt, orange-brown bole.",
    dimensions:
      "Overall: 21 7/16 × 14 3/4 in. (54.5 × 37.5 cm)\r\nSight: 5 × 5 1/8 in. (12.7 × 13 cm)",
    measurements: [
      {
        elementName: "Sight",
        elementDescription: null,
        elementMeasurements: {
          Height: 12.7,
          Width: 13,
        },
      },
      {
        elementName: "Overall",
        elementDescription: "Overall",
        elementMeasurements: {
          Height: 54.5,
          Width: 37.5,
        },
      },
    ],
    creditLine: "Robert Lehman Collection, 1975",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Frames",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-08-31T04:55:22.863Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/461607",
    tags: [
      {
        term: "Coat of Arms",
        AAT_URL: "http://vocab.getty.edu/page/aat/300126352",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q14659",
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: true,
    GalleryNumber: "954",
  },
  {
    objectID: 38237,
    isHighlight: true,
    accessionNumber: "2016.700",
    accessionYear: "2016",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/as/original/DP701399.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/as/web-large/DP701399.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/as/original/DP701401.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/DP701402.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/DP701400.jpg",
    ],
    constituents: null,
    department: "Asian Art",
    objectName: "Torso",
    title: "Buddha",
    culture: "South India (ancient Andhradesa, probably Nagarjunakonda)",
    period: "Ikshvaku period (ca. 225–ca. 320)",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "3rd century A.D.",
    objectBeginDate: 225,
    objectEndDate: 320,
    medium: "Limestone",
    dimensions:
      "H. 30 in. (76.2 cm); W. 11 in. (27.9 cm); D. 4 1/2 in. (11.4 cm); Est. Wt. 111.3 lbs (50.5 kg)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 11.4,
          Height: 76.2,
          Width: 27.9,
        },
      },
    ],
    creditLine:
      "Purchase, The Vincent Astor Foundation Gift, Brooke Russell Astor Bequest, The Miriam and Ira D. Wallach Foundation Fund; Fernando Family Trust Gift, in honor of Dr. Quintus and Mrs. Wimala Fernando; Vijay K. Anand, M.D., Nanda Anand, Maya Anand, and Rohit Anand, and The Estate of Mamdouha Bobst Gifts, 2016",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Sculpture",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-08-24T04:54:32.86Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/38237",
    tags: [
      {
        term: "Buddhism",
        AAT_URL: "http://vocab.getty.edu/page/aat/300073738",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q748",
      },
      {
        term: "Buddha",
        AAT_URL: "http://vocab.getty.edu/page/aat/300262950",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q7055",
      },
      {
        term: "Early Andhra",
        AAT_URL: "http://vocab.getty.edu/page/aat/300106839",
        Wikidata_URL: null,
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "235",
  },
  {
    objectID: 61658,
    isHighlight: false,
    accessionNumber: "34.15.1a, b",
    accessionYear: "1934",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/as/original/DP223478.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/as/web-large/DP223478.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/as/original/DP223481.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/DP223482.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/DP223480.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/DP222953.jpg",
      "https://images.metmuseum.org/CRDImages/as/original/DP222949.jpg",
    ],
    constituents: null,
    department: "Asian Art",
    objectName: "Figure",
    title: "Bodhisattva Avalokiteshvara (Guanyin)",
    culture: "China",
    period: "Yuan dynasty (1271–1368)",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "dated 1282",
    objectBeginDate: 1282,
    objectEndDate: 1282,
    medium:
      "Wood (wiillow) with traces of pigment; single woodblock construction",
    dimensions:
      "a) Guanyin: 39 1/4 in. (99.7 cm)\r\nb) Inscribed block: H. 6 1/2 in. (16.5 cm); W. 2 1/4 in. (5.7 cm); D. 1 in. (2.5 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: "a (Guanyin)",
        elementMeasurements: {
          Height: 99.7,
        },
      },
      {
        elementName: "Overall",
        elementDescription: "b (inscribed block)",
        elementMeasurements: {
          Depth: 2.54,
          Height: 16.51,
          Width: 5.715,
        },
      },
    ],
    creditLine: "Purchase, Joseph Pulitzer Bequest, 1934",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Sculpture",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-03-04T10:34:46.977Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/61658",
    tags: [
      {
        term: "Buddhism",
        AAT_URL: "http://vocab.getty.edu/page/aat/300073738",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q748",
      },
      {
        term: "Avalokiteshvara",
        AAT_URL: "http://vocab.getty.edu/page/ia/901000085",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q193849",
      },
      {
        term: "Bodhisattvas",
        AAT_URL: "http://vocab.getty.edu/page/aat/300264360",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q178149",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q83562686",
    isTimelineWork: true,
    GalleryNumber: "208",
  },
  {
    objectID: 544740,
    isHighlight: true,
    accessionNumber: "15.2.1",
    accessionYear: "1915",
    isPublicDomain: true,
    primaryImage:
      "https://images.metmuseum.org/CRDImages/eg/original/DT549.jpg",
    primaryImageSmall:
      "https://images.metmuseum.org/CRDImages/eg/web-large/DT549.jpg",
    additionalImages: [
      "https://images.metmuseum.org/CRDImages/eg/original/15.2.1_227910.jpg",
      "https://images.metmuseum.org/CRDImages/eg/original/15.2.1_227911.jpg",
      "https://images.metmuseum.org/CRDImages/eg/original/15.2.1_03.jpg",
    ],
    constituents: null,
    department: "Egyptian Art",
    objectName: "Statue, Yuny, Renenutet, pair, menat, music",
    title: "Yuny and His Wife Renenutet",
    culture: "",
    period: "New Kingdom, Ramesside",
    dynasty: "Dynasty 19",
    reign: "reign of Seti I",
    portfolio: "",
    artistRole: "",
    artistPrefix: "",
    artistDisplayName: "",
    artistDisplayBio: "",
    artistSuffix: "",
    artistAlphaSort: "",
    artistNationality: "",
    artistBeginDate: "",
    artistEndDate: "",
    artistGender: "",
    artistWikidata_URL: "",
    artistULAN_URL: "",
    objectDate: "ca. 1294–1279 B.C.",
    objectBeginDate: -1294,
    objectEndDate: -1279,
    medium: "Limestone, paint",
    dimensions:
      "H. 84.5 cm (33 1/4 in.); W. 54.5 cm (21 7/16 in.); D. 73 cm (28 3/4 in.)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 73,
          Height: 84.5,
          Width: 54.5,
        },
      },
    ],
    creditLine: "Rogers Fund, 1915",
    geographyType: "From",
    city: "",
    state: "",
    county: "",
    country: "Egypt",
    region: "Middle Egypt",
    subregion: "Asyut (Assiut, Siut; Lykopolis)",
    locale: "Tomb of Amenhotep",
    locus: "Necropolis Cliff tomb, Medjdeni",
    excavation: "Khashaba excavations, 1913",
    river: "",
    classification: "",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2021-04-04T04:57:29.037Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/544740",
    tags: [
      {
        term: "Couples",
        AAT_URL: "http://vocab.getty.edu/page/aat/300379217",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q219160",
      },
      {
        term: "Men",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025928",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q8441",
      },
      {
        term: "Women",
        AAT_URL: "http://vocab.getty.edu/page/aat/300025943",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q467",
      },
      {
        term: "Hieroglyphs",
        AAT_URL: "http://vocab.getty.edu/page/aat/300028721",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q193762",
      },
    ],
    objectWikidata_URL: "https://www.wikidata.org/wiki/Q29385834",
    isTimelineWork: false,
    GalleryNumber: "124",
  },
  {
    objectID: 825497,
    isHighlight: true,
    accessionNumber: "2019.556",
    accessionYear: "2019",
    isPublicDomain: false,
    primaryImage: "",
    primaryImageSmall: "",
    additionalImages: [],
    constituents: [
      {
        constituentID: 162294,
        role: "Artist",
        name: "Charles Ray",
        constituentULAN_URL: "http://vocab.getty.edu/page/ulan/500118700",
        constituentWikidata_URL: "https://www.wikidata.org/wiki/Q872846",
        gender: "",
      },
    ],
    department: "Modern and Contemporary Art",
    objectName: "Sculpture",
    title: "Two horses",
    culture: "",
    period: "",
    dynasty: "",
    reign: "",
    portfolio: "",
    artistRole: "Artist",
    artistPrefix: "",
    artistDisplayName: "Charles Ray",
    artistDisplayBio: "American, born Chicago, Illinois, 1953",
    artistSuffix: "",
    artistAlphaSort: "Ray, Charles",
    artistNationality: "American",
    artistBeginDate: "1953",
    artistEndDate: "9999",
    artistGender: "",
    artistWikidata_URL: "https://www.wikidata.org/wiki/Q872846",
    artistULAN_URL: "http://vocab.getty.edu/page/ulan/500118700",
    objectDate: "2019",
    objectBeginDate: 2019,
    objectEndDate: 2019,
    medium: "Granite",
    dimensions:
      "10 ft. 3/8 in. × 14 ft. 10 1/4 in. × 8 1/2 in. (305.8 × 452.8 × 21.6 cm)",
    measurements: [
      {
        elementName: "Overall",
        elementDescription: null,
        elementMeasurements: {
          Depth: 21.590044,
          Height: 305.7531,
          Width: 452.75592,
        },
      },
      {
        elementName: "Overall",
        elementDescription: "Estimated weight of sculpture and fixture",
        elementMeasurements: {
          Weight: 5896.761,
        },
      },
      {
        elementName: "Overall",
        elementDescription: "Estimated weight of sculpture",
        elementMeasurements: {
          Weight: 4535.97,
        },
      },
    ],
    creditLine:
      "Purchase, Lila Acheson Wallace Gift, Gift of Continental Group, by exchange, and Bequest of Gioconda King, by exchange, 2019",
    geographyType: "",
    city: "",
    state: "",
    county: "",
    country: "",
    region: "",
    subregion: "",
    locale: "",
    locus: "",
    excavation: "",
    river: "",
    classification: "Sculpture",
    rightsAndReproduction: "",
    linkResource: "",
    metadataDate: "2022-01-25T04:43:45.507Z",
    repository: "Metropolitan Museum of Art, New York, NY",
    objectURL: "https://www.metmuseum.org/art/collection/search/825497",
    tags: [
      {
        term: "Horses",
        AAT_URL: "http://vocab.getty.edu/page/aat/300250148",
        Wikidata_URL: "https://www.wikidata.org/wiki/Q726",
      },
    ],
    objectWikidata_URL: "",
    isTimelineWork: false,
    GalleryNumber: "918",
  },
];

export default data;
